services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    # Collection
    App\Collection\Application\Repository\CollectionRepository:
        '@App\Collection\Infrastructure\Collection\InMemory'

    # Game
    App\Game\Application\Repository\GameRepository:
        '@App\Game\Infrastructure\Game\InMemory'

    # Game details
    App\GameDetails\Application\Repository\GameDetailsRepository:
        '@App\GameDetails\Infrastructure\GameDetails\InMemory'