services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    # Game
    App\Game\Application\Repository\GameRepository:
        '@App\Game\Infrastructure\Game\InMemory'